import { Header, Sidebar } from "@/components";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div className="sticky w-[300px]">
            <Sidebar />
          </div>
          <div className="w-[100%] flex flex-col flex-1 z-1000">
            <div className="w-[100%] h-16">
              <Header />
            </div>
            <div className="px-12 pt-5">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
